# Generated by Django 3.1.4 on 2021-01-06 00:43

from django.db import migrations, models
import todos.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardId', models.CharField(max_length=128, unique=True, verbose_name='boardId')),
                ('boardTitle', models.CharField(max_length=64, unique=True, verbose_name='boardTitle')),
                ('listId', models.CharField(max_length=64, unique=True, verbose_name='listId')),
                ('listTitle', models.CharField(max_length=64, unique=True, verbose_name='listTitle')),
            ],
            managers=[
                ('objects', todos.managers.AimManager()),
            ],
        ),
    ]
